name: Publish Docker image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to AWS ECR and Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build and push Docker image to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          awsUrl=244530008913.dkr.ecr.eu-west-1.amazonaws.com
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin $awsUrl
          rev=$(git rev-parse --short HEAD)
          username=kaam004
          tag=kaam004frilekreact
          docker build . -t $tag:$rev
          docker tag $tag:$rev $awsUrl/$username:$rev
          docker tag $tag:$rev $awsUrl/$username:latest
          docker push $awsUrl/$username:$rev
          docker push $awsUrl/$username:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: kaikka/kaam004frilekreact

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kaam004frilekreact:latest
          labels: ${{ steps.meta.outputs.labels }}